pcl_processing:
  ros__parameters:
    # Values here are all in metres 
    robot_height: 0.9
    camera_height: 0.5
    camera_x_offset: 0.35
    camera_y_offset: 0.0
    #size of bounding box
    min_bound_x: -0.55
    max_bound_x: 1.2
    min_bound_y: -0.75
    max_bound_y: 0.75
    min_bound_z: -0.35
    max_bound_z: 1.0
    # min_bound_z: -1000.0
    # max_bound_z: 1000.0