pcl_processing:
  ros__parameters:
    # Topic name for the camera point cloud
    camera_topic: "/zed2/zed_node/point_cloud/cloud_registered"
    # Values here are all in metres
    # These values are the offset from center of robot to camera (phrase better)
    robot_height: 0.9              # Height of robot
    camera_height: 0.5             # Height of camera off the ground 
    camera_x_offset: 0.35          # Distance in meters of camera offset parallel to robot front
    camera_y_offset: 0.0           # Distance in meters of camera offset perpendicular to robot front
    points_to_add: 3               # How many partitions to split the point cloud into
    decay_time: 8.0                # Time in seconds for the ARCL added points to decay
    distance_threshold: 0.03       # Distance in meters to add a new point
    # Values here are in Radians
    camera_horizontal_fov: 2.0944  # camera point cloud horizontal FoV
    camera_yaw_offset: 0.0
    # Size of bounding box
    # Note that ZED2 point cloud faces the x-axis,
    # Looking Forward would be increasing distance in the x-axis
    min_bound_x: -0.55
    max_bound_x: 2.5
    min_bound_y: -0.75
    max_bound_y: 0.75
    min_bound_z: -0.35
    max_bound_z: 1.0
